Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  node_prefix = `whoami`.strip

  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 4096
    libvirt.cpus = 2
  end

  # Partage du dossier pour libvirt (NFSv4 TCP, UDP désactivé sur kernels récents)
  config.vm.synced_folder "./", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false

  config.vm.define "#{node_prefix}S" do |node|
    node.vm.hostname = "#{node_prefix}S"
    node.vm.network "private_network", ip: "192.168.56.110"
    node.vm.network "forwarded_port", guest: 80, host: 8080
    node.vm.provision "shell", path: "./scripts/Server.sh", args: ['192.168.56.110']
  end
end