#!/bin/bash

#globals
export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get install -y curl iptables

MASTER_IP="$1"
NODE_IP="$2"

# Recovering token
echo "[LOG] - Waiting for token file to be generated by server..."
TIMEOUT=180
while [ ! -f /vagrant/k3s_token ]; do 
    sleep 1
    TIMEOUT=$((TIMEOUT - 1))
    if [ "$TIMEOUT" -eq 0 ]; then
        echo "Load Token file failed."
        exit 1
    fi 
done

# Wait until token CA hash matches the actual server CA hash.
echo "[LOG] - Validating token hash against server CA..."
TIMEOUT=180
while true; do
    K3S_TOKEN=$(cat /vagrant/k3s_token)
    TOKEN_HASH=$(echo "$K3S_TOKEN" | sed -n "s/^K10\([a-f0-9]\{64\}\)::server:.*/\1/p")
    CA_HASH=$(curl -ks https://"$MASTER_IP":6443/cacerts | sha256sum | awk '{print $1}')

    if [ -n "$TOKEN_HASH" ] && [ -n "$CA_HASH" ] && [ "$TOKEN_HASH" = "$CA_HASH" ]; then
        break
    fi

    sleep 2
    TIMEOUT=$((TIMEOUT - 2))
    if [ "$TIMEOUT" -le 0 ]; then
        echo "Token/CA hash mismatch timeout."
        echo "Token hash: $TOKEN_HASH"
        echo "CA hash:    $CA_HASH"
        exit 1
    fi
done

# Install k3s agent
echo "[LOG] - Installing k3s agent"
INTERFACE=$(ip -o -4 addr show | awk -v ip="$NODE_IP" '$0 ~ ip {print $2}')

# Configure persistent agent settings (portable across interface naming).
mkdir -p /etc/rancher/k3s
sed -e "s/__NODE_IP__/$NODE_IP/g" -e "s/__FLANNEL_IFACE__/$INTERFACE/g" \
    /vagrant/confs/Worker.yaml.tpl > /etc/rancher/k3s/config.yaml

export K3S_TOKEN
export K3S_URL=https://$MASTER_IP:6443
curl -sfL https://get.k3s.io | sh -
if [ $? -ne 0 ]; then
    echo "Failed to install k3s. Exiting."
    exit 1
fi

echo 'export PATH="/sbin:$PATH"' >> $HOME/.bashrc
echo "alias k='kubectl'" | sudo tee /etc/profile.d/00-aliases.sh > /dev/null